/**
 * Default UI labels — used as fallback when Supabase is unreachable
 * and no localStorage cache exists. Keep in sync with ui_labels table.
 */
export const DEFAULT_LABELS = {
  // ── Navigation ──
  'nav.dashboard': 'Dashboard',
  'nav.allStudents': 'All Students',
  'nav.addStudent': 'Add Student',
  'nav.sanadRecords': 'Sanad Records',
  'nav.rooms': 'Rooms',
  'nav.classes': 'Classes',
  'nav.results': 'Results',
  'nav.grading': 'Grading',
  'nav.auditLog': 'Audit Log',
  'nav.collapse': 'Collapse',
  'nav.expand': 'Expand',

  // ── Dashboard ──
  'dash.title': 'Dashboard Overview',
  'dash.subtitle': 'Real-time student analytics at a glance',
  'dash.totalStudents': 'Total Students',
  'dash.districts': 'Districts',
  'dash.classes': 'Classes',
  'dash.avgPerClass': 'Avg per Class',
  'dash.studentsByClass': 'Students by Class',
  'dash.recentStudents': 'Recent Students',
  'dash.noClassData': 'No class data yet',
  'dash.noClassesFound': 'No classes found',
  'dash.noStudents': 'No students found.',
  'dash.refresh': 'Refresh',

  // ── Student Table Headers ──
  'table.serialNo': 'Serial No',
  'table.name': 'Name',
  'table.fatherName': 'Father Name',
  'table.type': 'Type',
  'table.class': 'Class',
  'table.district': 'District',
  'table.cnic': 'CNIC',
  'table.status': 'Status',
  'table.active': 'Current',
  'table.inactive': 'Rusticated',
  'table.passed': 'Passed',

  // ── Student Form — Section Titles ──
  'form.basicInfo': '👤 Basic Information — بنیادی معلومات',
  'form.enrollment': '🎓 Enrollment Details — تفصیلات داخلہ',
  'form.guardian': '👨‍👩‍👦 Guardian Information — ولی / سرپرست کی معلومات',
  'form.residence': '📍 Residence & Location — رہائش اور مقام',

  // ── Student Form — Field Labels ──
  'form.studentImage': 'Student Image (تصویر طالب علم)',
  'form.fullName': 'Full Name (نام) *',
  'form.fatherName': "Father's Name (ولدیت) *",
  'form.dob': 'Date of Birth (تاریخ پیدائش)',
  'form.cnic': 'Student CNIC / B-Form No.',
  'form.phone': 'Phone Number (فون نمبر)',
  'form.studentType': 'Student Type *',
  'form.classLevel': 'Class / Level (درجہ)',
  'form.entryYear': 'Entry Year (سالِ داخلہ)',
  'form.admissionDate': 'Admission Date (تاریخِ داخلہ)',
  'form.leavingDate': 'Leaving Date (تاریخِ اجراء)',
  'form.serialNo': 'Serial No. (سلسلہ نمبر)',
  'form.formNo': 'Form No. (فارم نمبر)',
  'form.guardianName': "Guardian's Name",
  'form.guardianRelation': 'Relation (رشتہ)',
  'form.guardianCnic': 'Guardian CNIC No.',
  'form.guardianPhone': "Guardian's Phone",
  'form.residentialStatus': 'Residential Status (مقیم/غیرمقیم)',
  'form.roomNumber': 'Room Number (کمرہ نمبر)',
  'form.districtField': 'District (ضلع) *',
  'form.address': 'Address (پتہ)',
  'form.removeImage': '🗑️ Remove Image',
  'form.bloodGroup': 'بلڈ گروپ',
  'form.previousInstitution': 'سابقہ ادارے کا نام',
  'form.previousStudies': 'سابقہ تعلیم کی تفصیل',
  'form.lastYearMarks': 'گزشتہ سال کے نمبرات',
  'form.miyarEKamyabi': 'معیارِ کامیابی',

  // ── Student Form — Select Options ──
  'form.selectType': '— Select Type —',
  'form.selectClass': '— Select Class —',
  'form.selectRelation': '— Select Relation —',
  'form.selectResidence': '— Select —',
  'form.resident': 'مقیم (Resident)',
  'form.nonResident': 'غیر مقیم (Non-Resident)',
  'form.selectRoom': '— Select Room —',

  // ── Add / Edit Student ──
  'add.title': 'Add New Student',
  'add.subtitle': 'Fill in the details below to register a student',
  'add.save': '➕ Save Student',
  'add.print': '🖨️ Print Form',
  'add.printHint': 'Fill Name, CNIC & District to enable printing',
  'add.offline': 'You are offline',
  'add.offlineMsg': 'Adding students requires an internet connection. Please reconnect and try again.',
  'edit.title': '✏️ Edit Student',
  'edit.save': '💾 Save Changes',
  'edit.cancel': '← Cancel',
  'edit.offline': 'You are offline',
  'edit.offlineMsg': 'Editing students requires an internet connection. Please reconnect and try again.',

  // ── All Students Section ──
  'all.title': 'All Students',
  'all.showInactive': 'Show All',
  'all.exportReport': '📄 Export Report',
  'all.closeReport': 'Close Report',
  'all.searchPlaceholder': 'Search… Enter to open (Ctrl+F)',
  'all.noMatch': 'No students match your search.',
  'all.noStudents': 'No students found',

  // ── Report ──
  'report.title': '📄 Report Configuration',
  'report.filters': '🔧 Filters',
  'report.filtersHint': '— at least one required',
  'report.studentType': 'Student Type',
  'report.class': 'Class',
  'report.district': 'District',
  'report.entryYear': 'Entry Year',
  'report.roomNo': 'Room No.',
  'report.status': 'Status',
  'report.allTypes': 'All Types',
  'report.allDistricts': 'All Districts',
  'report.allYears': 'All Years',
  'report.allRooms': 'All Rooms',
  'report.all': 'All',
  'report.activeOnly': 'Current only',
  'report.inactiveOnly': 'Rusticated only',
  'report.passedOnly': 'Passed only',
  'report.columns': 'Columns',
  'report.photoWarning': '⚠ Photos make PDF slower',
  'report.preview': '👁 Preview Report',
  'report.download': '📥 Download PDF',
  'report.print': '🖨️ Print',
  'report.noStudents': 'No students found with the selected filters',
  'report.filterRequired': '⚠ Select at least one filter',

  // ── Report Field Labels ──
  'field.student_image': 'Photo',
  'field.status': 'Status',
  'field.student_type': 'Student Type',
  'field.serial_no': 'Serial No',
  'field.entry_year': 'Entry Year',
  'field.name': 'Name',
  'field.father_name': 'Father Name',
  'field.dob_raw': 'DOB Raw',
  'field.dob': 'DOB',
  'field.class_level': 'Class',
  'field.district': 'District',
  'field.address': 'Address',
  'field.residential_status': 'Resident Status',
  'field.cnic': 'CNIC',
  'field.guardian_phone': 'Guardian Phone',
  'field.form_no': 'Form No',
  'field.phone': 'Phone',
  'field.source_sheet': 'Source Sheet',
  'field.source_row': 'Source Row',
  'field.tareekh_daakhla': 'Tareekh Daakhla',
  'field.tareekh_ijaara': 'Tareekh Ijaara',
  'field.guardian_relation': 'Guardian Relation',
  'field.guardian_cnic': 'Guardian CNIC',
  'field.room_number': 'Room Number',
  'field.guardian_name': 'Guardian Name',
  'field.blood_group': 'بلڈ گروپ',
  'field.previous_institution': 'سابقہ ادارہ',
  'field.previous_studies': 'سابقہ تعلیم',
  'field.last_year_marks': 'گزشتہ سال نمبرات',
  'field.miyar_e_kamyabi': 'معیارِ کامیابی',

  // ── Dropdown Options ──
  'opt.studentTypes': JSON.stringify(['kutub', 'naazrah', 'hifz', 'fuzala', 'sanad']),
  'opt.guardianRelations': JSON.stringify([
    { value: 'والد', label: 'Father (والد)' },
    { value: 'بھائی', label: 'Brother (بھائی)' },
    { value: 'چچا', label: 'Uncle — Paternal (چچا)' },
    { value: 'ماموں', label: 'Uncle — Maternal (ماموں)' },
    { value: 'دادا', label: 'Grandfather (دادا)' },
    { value: 'نانا', label: 'Maternal Grandfather (نانا)' },
    { value: 'سرپرست', label: 'Guardian (سرپرست)' },
    { value: 'دیگر', label: 'Other (دیگر)' },
  ]),

  // ── Rooms ──
  'rooms.title': 'Rooms Management',
  'rooms.addRoom': '➕ Add Room',
  'rooms.back': '← Back',
  'rooms.newRoom': 'New Room',
  'rooms.editRoom': 'Edit Room',
  'rooms.roomNumber': 'Room Number *',
  'rooms.capacity': 'Capacity (total beds)',
  'rooms.occupancy': 'Current Occupancy',
  'rooms.notes': 'Notes',
  'rooms.roomImage': 'Room Image',
  'rooms.addBtn': '🚪 Add Room',
  'rooms.saveBtn': '💾 Save Changes',
  'rooms.cancel': 'Cancel',
  'rooms.deleteConfirm': 'Delete this room?',
  'rooms.edit': '✏️ Edit',
  'rooms.delete': '🗑️ Delete',
  'rooms.viewStudents': '👥 View Students',
  'rooms.full': 'FULL',
  'rooms.searchPlaceholder': '🔍 Search by room number...',
  'rooms.noRooms': 'No rooms added yet.',
  'rooms.noMatch': 'No rooms matching',

  // ── Classes ──
  'classes.title': 'کلاسیں',
  'classes.subtitle': 'تمام کلاسیں اور ان کے وظائف',
  'classes.addTitle': 'نئی کلاس شامل کریں',
  'classes.className': 'کلاس کا نام',
  'classes.sortOrder': 'ترتیب نمبر (اختیاری)',
  'classes.addBtn': '➕ شامل کریں',
  'classes.adding': 'شامل ہو رہا ہے…',
  'classes.allClasses': 'تمام کلاسیں',
  'classes.noClasses': 'کوئی کلاس نہیں ملی',
  'classes.wazifa': 'وظیفہ',
  'classes.wazifaPlaceholder': 'وظیفہ درج کریں',
  'classes.save': '💾 محفوظ',
  'classes.report': '📄 رپورٹ',
  'classes.actions': 'عمل',
  'classes.refresh': 'تازہ کریں',
  'classes.loading': 'کلاسیں لوڈ ہو رہی ہیں…',
  'classes.saved': 'تبدیلیاں محفوظ ہو گئیں',
  'classes.emptyName': 'کلاس کا نام خالی نہیں ہو سکتا',

  // ── Sanad ──
  'sanad.title': 'Sanad Records',
  'sanad.subtitle': 'Track historical progress and qualifications',
  'sanad.viewAll': '📋 View All',
  'sanad.addRecord': '➕ Add Record',
  'sanad.saveRecord': '➕ Save Sanad Record',
  'sanad.basicDetails': '📋 Basic Details',
  'sanad.levelsProgress': '🎓 Sanad Levels Progress',
  'sanad.serialNo': 'Serial No.',
  'sanad.entryDate': 'Entry Date',
  'sanad.nameWithFather': 'Name w/ Father *',
  'sanad.district': 'District',
  'sanad.studentId': 'Related Student ID',
  'sanad.sourceRow': 'Source Row',
  'sanad.noRecords': 'No Sanad records found.',
  'sanad.searchPlaceholder': 'Search name, district, serial no…',

  // ── Topbar ──
  'topbar.welcome': 'Welcome,',
  'topbar.syncing': '🔄 Syncing…',
  'topbar.online': '🟢 Online',
  'topbar.offline': '🔴 Offline',
  'topbar.notSynced': 'Not synced yet',
  'topbar.logout': 'Logout',

  // ── Print Form (Urdu) ──
  'print.title': 'دارالعلوم اسلامیہ',
  'print.formTitle': 'فارمِ داخلہ',
  'print.personalSection': 'ذاتی معلومات',
  'print.formNo': 'فارم نمبر:',
  'print.serialNo': 'سلسلہ نمبر:',
  'print.date': 'تاریخ:',
  'print.fullName': 'مکمل نام',
  'print.fatherName': 'ولدیت',
  'print.dob': 'تاریخ پیدائش',
  'print.cnic': 'شناختی کارڈ / بی فارم نمبر',
  'print.phone': 'فون نمبر',
  'print.enrollmentSection': 'تفصیلاتِ داخلہ',
  'print.studentType': 'قسمِ طالب علم',
  'print.classLevel': 'درجہ',
  'print.entryYear': 'سالِ داخلہ',
  'print.admissionDate': 'تاریخِ داخلہ',
  'print.bloodGroup': 'بلڈ گروپ',
  'print.previousInstitution': 'سابقہ ادارہ',
  'print.previousStudies': 'سابقہ تعلیم کی تفصیل',
  'print.lastYearMarks': 'گزشتہ سال نمبرات',
  'print.miyarEKamyabi': 'معیارِ کامیابی',
  'print.guardianSection': 'ولی / سرپرست کی تفصیل',
  'print.guardianName': 'ولی کا نام',
  'print.relation': 'رشتہ',
  'print.guardianCnic': 'ولی کا شناختی کارڈ',
  'print.guardianPhone': 'ولی کا فون نمبر',
  'print.residenceSection': 'رہائش اور مقام',
  'print.residentialStatus': 'رہائشی حیثیت',
  'print.district': 'ضلع',
  'print.roomNumber': 'کمرہ نمبر',
  'print.address': 'پتہ',
  'print.studentSig': 'طالب علم کے دستخط',
  'print.guardianSig': 'ولی کے دستخط',
  'print.principalSig': 'مہتمم کے دستخط',
  'print.footer': 'دارالعلوم اسلامیہ — نظامِ انتظامِ طلباء',
  'print.printBtn': '🖨️ پرنٹ کریں',
  'print.closeBtn': '✕ بند کریں',

  // ── Wazifa Report ──
  'wazifa.reportTitle': 'وظیفہ حاضری رپورٹ',
  'wazifa.classLabel': 'درجہ:',
  'wazifa.monthLabel': 'مہینہ:',
  'wazifa.totalStudents': 'کل طلباء:',
  'wazifa.wazifaLabel': 'وظیفہ',
  'wazifa.noWazifa': '(وظیفہ درج نہیں)',
  'wazifa.colNumber': 'نمبر',
  'wazifa.colName': 'نام طالب علم',
  'wazifa.colFather': 'ولدیت',
  'wazifa.colWazifa': 'وظیفہ',
  'wazifa.colSignature': 'دستخط',
  'wazifa.footer': 'دارالعلوم اسلامیہ — نظام انتظام طلباء',
  'wazifa.printBtn': '🖨️ پرنٹ کریں',
  'wazifa.closeBtn': '✕ بند کریں',
}
