export const STUDENT_TYPES = ['kutub', 'naazrah', 'hifz', 'fuzala', 'sanad']

export const PAGE_SIZE = 50

export const CLASS_OPTIONS = [
  'عالمیہ ثانیہ',
  'عالمیہ اولیٰ',
  'عالیہ ثانیہ',
  'عالیہ اولیٰ',
  'خاصہ ثانیہ',
  'خاصہ اولیٰ',
  'عامہ ثالثہ',
  'عامہ ثانیہ کمپیوٹر سائنس',
  'عامہ ثانیہ بائیو سائنس',
  'عامہ ثانیہ آرٹس',
  'دراسات دینیہ اول',
  'دراسات دینیہ دوم',
  'عامہ اولیٰ الف',
  'عامہ اولیٰ کمپیوٹر سائنس',
  'عامہ اولیٰ بائیو سائنس',
  'عامہ اولیٰ آرٹس',
  'اعدادیہ برائے عامہ اولیٰ',
  'متوسطہ ثالثہ (8th)',
  'متوسطہ ثانیہ (7th)',
  'متوسطہ اولیٰ (6th)',
  'حفظ',
  'ناظرہ',
]



export const GUARDIAN_RELATIONS = [
  { value: 'والد', label: 'Father (والد)' },
  { value: 'بھائی', label: 'Brother (بھائی)' },
  { value: 'چچا', label: 'Uncle — Paternal (چچا)' },
  { value: 'ماموں', label: 'Uncle — Maternal (ماموں)' },
  { value: 'دادا', label: 'Grandfather (دادا)' },
  { value: 'نانا', label: 'Maternal Grandfather (نانا)' },
  { value: 'سرپرست', label: 'Guardian (سرپرست)' },
  { value: 'دیگر', label: 'Other (دیگر)' },
]

export const REPORT_FIELDS = {
  student_image: 'Photo',
  status: 'Status',
  student_type: 'Student Type',
  serial_no: 'Serial No',
  entry_year: 'Entry Year',
  name: 'Name',
  father_name: 'Father Name',
  dob_raw: 'DOB Raw',
  dob: 'DOB',
  class_level: 'Class',
  district: 'District',
  address: 'Address',
  residential_status: 'Resident Status',
  cnic: 'CNIC',
  guardian_phone: 'Guardian Phone',
  form_no: 'Form No',
  phone: 'Phone',
  source_sheet: 'Source Sheet',
  source_row: 'Source Row',
  tareekh_daakhla: 'Tareekh Daakhla',
  tareekh_ijaara: 'Tareekh Ijaara',
  guardian_relation: 'Guardian Relation',
  guardian_cnic: 'Guardian CNIC',
  room_number: 'Room Number',
  guardian_name: 'Guardian Name',
  blood_group: 'Blood Group',
  previous_institution: 'Previous Institution',
  previous_studies: 'Previous Studies',
  last_year_marks: 'Last Year Marks',
  miyar_e_kamyabi: 'Miyar e Kamyabi',
}

export const initialStudent = {
  status: 'current',
  student_type: 'kutub',
  serial_no: '',
  entry_year: '',
  name: '',
  father_name: '',
  dob_raw: '',
  dob: '',
  class_level: '',
  district: '',
  address: '',
  residential_status: '',
  cnic: '',
  guardian_phone: '',
  form_no: '',
  phone: '',
  source_sheet: '',
  source_row: '',
  tareekh_daakhla: '',
  tareekh_ijaara: '',
  guardian_relation: '',
  guardian_cnic: '',
  room_number: '',
  guardian_name: '',
  student_image: '',
  student_image_file: null,
  blood_group: '',
  previous_institution: '',
  previous_studies: '',
  last_year_marks: '',
  miyar_e_kamyabi: '',
}
